### ISSUE TITLE
Question: Is it possible to use rofi-code as a rofi mode?

### ISSUE THREAD

**Issue by Kuxe** [Coffelius/rofi-code#2]
I'm using rofi like this:

```
rofi -modi drun,window,filebrowser,ssh,emoji -show drun
```
This command is mapped to a key combination via my window manager i3.

It'd be cool if it was possible to use rofi-code this way too. I tried

```
rofi -modi drun,window,filebrowser,ssh,emoji,code -show drun
```

but that failed since "code" is not a known mode.

Is it possible to use rofi-code as a mode? That way I could just launch rofi and switch over to the "code"-tab without having to memorize a specific shortcut for rofi-code.

**Comment by Coffelius** [comment]
Hi Kuxe,
the short answer is no.

A longer answer is that rofi-code works with rofi in [dmenu mode](https://github.com/davatorium/rofi/blob/next/doc/rofi-dmenu.5.markdown) and it is not possible to launch rofi in dmenu mode together with other modes (window, emoji, run, etc).

I have done a quick research to find out what would be the easiest way to use rofi-code as a plugin and I didn't find anything that doesn't require some work. But, what I believe is the shortest path to get what you want is using https://github.com/marvinkreis/rofi-json-menu

This rofi plugin loads a json file and shows it. With some script converting the output of `rofi-code -o` to the proper json scheme before rofi is launched, it would be possible to get the workspace list switchable with "code"-tab.

I've also noticed that the rofi json plugin consists of a single C file that could be modified to work with rofi-code directly. However this would require some more work which seems like a lot of fun to do at some point with enough free time.

**Comment by Kuxe** [comment]
Alright, well I ended up writing a small bash-script that rofi can call. The script is simple and should be easily adaptable by anyone but it may not work out of the box since I make some assumptions that are not true in general. If anyone's interested here it is: https://gist.github.com/Kuxe/976d4765ee520c88d336fa1fefe01dc6
